global using FluentAssertions;
global using MarcusPrado.Platform.Abstractions.Search;
global using MarcusPrado.Platform.OpenSearch.Extensions;
global using MarcusPrado.Platform.OpenSearch.Options;
global using MarcusPrado.Platform.OpenSearch.Search;
global using Microsoft.Extensions.DependencyInjection;
global using NSubstitute;
global using OpenSearch.Client;
global using Xunit;
